project_id = "aceywpdeahxkbgzshiex"

[functions.create-admin-user]
verify_jwt = false

[functions.scrape-news-metadata]
verify_jwt = false

[functions.google-translate]
verify_jwt = false

[functions.detect-location]
verify_jwt = false